# Generated by Django 4.1.5 on 2023-01-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_name_alter_amenity_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.RemoveField(
            model_name="room",
            name="toliets",
        ),
        migrations.AddField(
            model_name="room",
            name="toilets",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
