# Generated by Django 4.1.5 on 2023-01-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="address",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="experience",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
